import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { renderMetaTags, StructuredText } from "react-datocms";
import { request } from '../lib/datocms'


export default function Home({ startpage }) {

  console.log(startpage)

  return (
    <div className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* {renderMetaTags(startPage.seo.concat(data.site.favicon))} */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1></h1>
      <div style={{ maxWidth: '800px' }}>
        <img src={startpage?.mainImage?.url} alt="consid commerce image" style={{ width: '100%' }} />
        <StructuredText data={startpage?.content?.value} />
      </div>
    </div>
  )
}

const HOMEPAGE_QUERY = `
query GetStartPage {
  startpage {
    content {
      value
    }
    title
    id
    mainImage {
      url
      alt
    }
  }
}

`;

export async function getStaticProps() {
  const data = await request({
    query: HOMEPAGE_QUERY,
    // variables: { limit: 10 }
  });
  return {
    props: data
  };
}