import Head from 'next/head'
import styles from '../styles/Products.module.css'
import { request } from '../lib/datocms';
import Link from 'next/link';

export default function Products(props) {

  const { allProducts } = props;
  return (
    <div className={styles.main}>
      <Head>
        <title>Consid Commerce | Products</title>
        <meta name="description" content="Generated by create next app" />
        {/* {renderMetaTags(startPage.seo.concat(data.site.favicon))} */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        Products
      </h1>
      {allProducts.map(product =>
        <div key={product.id} style={{ maxWidth: '400px' }}>
          <Link href={`/product/${product.id}`}>
            <img src={product.mainImage.url} alt="" style={{ width: '100%' }} />
            <h2>{product.name}</h2>
          </Link>
          <p>{product.price}</p>
        </div>)}
    </div>
  )
}





const PRODUCTS_QUERY = `
 query GetAllProducts{
  allProducts {
    id
    name
    price
    description {
      value
    }
    alternativeImages {
      url
    }
    mainImage {
      url
    }
  }
}

`


export const getStaticProps = async () => {

  const products = await request({
    query: PRODUCTS_QUERY
  })

  return {
    props: products
  }

}