import Head from 'next/head'
import styles from '../styles/Products.module.css'
import { request } from '../lib/datocms';
import Link from 'next/link';
import ProductCard from '../components/products/ProductCard';

export default function Products(props) {

  const { allProducts } = props;
  return (
    <div className={styles.main}>
      <Head>
        <title>Consid Commerce | Products</title>
        <meta name="description" content="Generated by create next app" />
        {/* {renderMetaTags(startPage.seo.concat(data.site.favicon))} */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.test}></div>
      <div className={styles.grid}>
        {/* <p>1</p>
        <p>2</p>
        <p>3</p>
        <p>4</p>
        <p>5</p>
        <p>6</p> */}
      </div>
      <h1>
        Products
      </h1>
      {allProducts.map(product =>
      (
        <ProductCard key={product.id} product={product} />
      ))}
    </div>
  )
}





const PRODUCTS_QUERY = `
 query GetAllProducts{
  allProducts {
    id
    name
    price
    description {
      value
    }
    alternativeImages {
      url
    }
    mainImage {
      url
    }
  }
}

`


export const getStaticProps = async () => {

  const products = await request({
    query: PRODUCTS_QUERY
  })

  return {
    props: products
  }

}